# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
author: Sean Feeney
copyright: cc by-nc-sa
title: The Feeney Genealogy Project
description: The Feeney Genealogy Project provides genealogy information on the Feeney, Feeny and O'Feeny Irish surname originating from Co. Sligo, Ireland.
keywords: feeney, feeny, o'feeny, genealogy, surname, ireland, irish, family, tree, clan, sligo, easky, easkey, owenbeg, tireragh, tireril
lang: en-US
google_analytics: G-YS7H39M430

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://feeneygenealogy.com" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:title:output_ext

logo: /assets/img/logo.jpg

twitter_username: SeanFromIT
facebook_username: seanfromit
linkedin_username: seanfromit
github_username: SeanFromIT
stack_overflow_username: 311393/seanfromit
angellist_username: seanfromit
slideshare_username: SeanFeeney3

twitter:
  username: SeanFromIT
  card: summary

social:
  name: Sean Feeney
  links:
    - https://twitter.com/SeanFromIT
    - https://www.facebook.com/seanfromit
    - https://www.linkedin.com/in/seanfromit
    - https://github.com/SeanFromIT
    - https://angel.co/seanfromit
    - https://stackexchange.com/users/311393/seanfromit
    - https://www.slideshare.net/SeanFeeney3

# Build settings
#incremental: true
markdown: kramdown
sass:
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
